# Welcome to PyRun!

# Need to install more packages? Just edit this file.

# Add packages from conda-forge under "dependencies:"
# Packages from PyPI should be added under "pip:"

name: base
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipywidgets
  - git
  - dask
  - dask-cloudprovider
  - zarr
  - xarray
  - s3fs
  - gcsfs
  - cftime
  - nc-time-axis
  - papermill
  - notebook
  - matplotlib
  - xhistogram
  - pip:
    - xarray
